### PR TITLE
Use multithreading for Condition instead of threading in order to han…

### PR DESCRIPTION
**Pull request by diorcety**
…dle signal interruptions
cf #115

### CODE REVIEW

**Comment by dbrattli** [comment]
Thanks. I'm going to have a look at this PR this weekend. Just want to check that there is no perf degradation. We might need a wrapper for it in the config similar to `Lock`, but I can take care of that.

**Comment by diorcety** [comment]
?

**Comment by dbrattli** [comment]
Had to revert since it broke develop. https://travis-ci.org/ReactiveX/RxPY/builds/155705742

**Comment by diorcety** [comment]
Strange, Travis on my PR was good

**Pull request merged**
