### PR TITLE
Better error handling for on_callable

### PR DESCRIPTION
**Pull request by mako-taco**
We're currently passing the type of `Exception` to `on_error`, instead of the instance of the exception that was caught.

### CODE REVIEW

**Comment by thomasnield** [comment]
Good catch. My bad.

**Comment by mako-taco** [comment]
it's possible that we should be saving a traceback when we do this so things aren't impossible to debug when the callable throws, too.

**Comment by thomasnield** [comment]
If you have a helpful way to do that, please put in another PR and we'll take a look! 

Sorry progress has been slow this summer. Dag and I have both been busy.

**Comment by mako-taco** [comment]
Np, thanks for the wonderful port. Another PR will be there soon.

**Comment by mako-taco** [comment]
Np, thanks for the wonderful port. Another PR will be there soon.

**Pull request merged**
