### PR TITLE
Fixing intermittent test failures

### PR DESCRIPTION
**Pull request by AXGKl**
Hi Dag, still spottet intermittent build breaks with the marbles test. This should fix it.

Sorry for that... :-/

### CODE REVIEW

**Comment by AXGKl** [comment]
conflict, closing, will send a new one. git still troubles me (I'm from the hg camp) .

**Comment by dbrattli** [comment]
I've also added some fixes to the marbles test. There were problems with marbles such as "1-2-3|", generating race on the last two values. Sometimes "1-2-|". I've added 10 ms between such values to keep them apart and in the right order.

**Comment by dbrattli** [comment]
Also, make sure all pull requests are against develop branch

**Comment by rgbkrk** [comment]
> Also, make sure all pull requests are against develop branch

@dbrattli to make this easier on contributors, you can set your default branch in the settings on the repo:

screen shot 2016-12-19 at 8 36 35 am

**Comment by AXGKl** [comment]
> Also, make sure all pull requests are against develop branch

Oh sorry, did not know your policies (ack to @rgbkrk)

I'll close the newest PR and send a new one on development branch.

Sorry again,
G.

**Pull request closed without merging**
