### PR TITLE
Make sure both class and __init__ docstring are included

### PR DESCRIPTION
**Pull request by erikkemperman**
As mentioned in https://github.com/ReactiveX/RxPY/issues/270#issuecomment-498248593.

By the way, I'm getting warnings about the guzzle theme, it appears they're using an outdated means of injecting script. I've created [an issue](https://github.com/guzzle/guzzle_sphinx_theme/issues/45).

Also, as part of the "final pass" of the docs, I think it would be good to change references to classes and methods using the appropriate markup, this will render them properly and link where possible.

And speaking about links, I will see if I can get the cross-links to work for function parameter types, today. I think that would be a great improvement, but maybe that's just me...

### CODE REVIEW

**Comment by MainRo** [comment]
> Also, as part of the "final pass" of the docs, I think it would be good to change references to classes and methods using the appropriate markup, this will render them properly and link where possible.

Sure. I thought I used the correct syntax (I did not find another way to do it). If this is not correct let's fix it.

**Comment by erikkemperman** [comment]
>  I thought I used the correct syntax

It's something like ```:class:`MyClass` ```I think, although it would sometimes need package prefix as well. I'm not saying it was done incorrectly, by the way, just that I notice some class names and functions which are not yet annotated this way.

I tried again to make the cross-linking work for function arguments and return types, but I guess I simply don't understand why the `sphinx-apidoc`-generated .rst files work and the manual ones that we have currently don't work.

So, I don't know how to resolve this... Well, I'm assuming that we don't want to throw away all the manually organized in favour of a boring tree like [this](https://github.com/erikkemperman/RxPY/tree/apidoc):

Screenshot from 2019-06-04 13-02-35

**Comment by erikkemperman** [comment]
Actually, on second thought... In addition to `__init__`, perhaps *all* dunderscore methods ought to be included, if docstrings are provided?

```python
# Include a separate entry for special methods, like __init__, where provided.
autodoc_default_options = {
    'member-order': 'bysource',
    'special-members': True,
    'exclude-members': '__dict__,__weakref__'
}
```

**Comment by erikkemperman** [comment]
@MainRo Yes I guess I would like all dunderscore methods, when docstrings are provided, should be included by sphinx. I've amended this PR, but since it changed after you approved it, maybe you want to reconsider or reaffirm?

**Comment by erikkemperman** [comment]
Thanks!

**Pull request merged**
