### PR TITLE
Fix race condition in zip operator

### PR DESCRIPTION
**Pull request by mmpio**
I have faced race conditions using the zip operator.
The list which stores the zipped observables values may be accessed concurrently, thus, checking and popping data from that list shall be done in an atomic way.

### CODE REVIEW

**Comment by mmpio** [comment]
@MainRo 
I was wondering that too. But if for any reason, zip is called with no arguments, then we'll face a "tuple index out of range" trying to access args[0].lock.

If you decide to keep the solution I've submitted, the lock may even be created in the subscribe function. I don't know what is the best implementation.

**Comment by jcafhe** [comment]
I believe source locks are just helpers, so I guess you may use a local lock with no issue. 

@mmpio @MainRo  I was wondering if appending value to that same list should be controlled by the same lock too?
https://github.com/ReactiveX/RxPY/blob/82bc96059ab9f4ed0d0c93a15095c175fcff0e5d/rx/core/observable/zip.py#L63-L65

**Comment by mmpio** [comment]
@jcafhe I think it is a good idea to move the 'synchronized' decorator from the 'next' function to the 'on_next' function. As the latter is the only one to call the first, the performance will be the same, but at least we won't need to think about the thread issues that may rise without the lock control on appending.

Speaking about performances, the zip operator also runs way faster with the lock, at least in my sample code #505

**Comment by jcafhe** [comment]
> Speaking about performances, the zip operator also runs way faster with the lock, at least in my sample code #505

Indeed, on my laptop and a sleep time of 1s, I get around 500-800 values without the lock, and ~25000 values with the lock.

Also, I was thinking that we generally use a re-entrant lock, i.e. `threading.Rlock` instead of a `threading.Lock`. I don't know if it' mandatory here, but there may be some corner cases especially with some recursive mechanisms in rx. What do you think?

**Comment by MainRo** [comment]
🤔 how can you have much better performances with an additional lock ? That is strange. What bench do you run ?

Concerning the lock on append, this is an atomic operation (https://docs.python.org/3/faq/library.html#what-kinds-of-global-value-mutation-are-thread-safe), so we could keep the lock only on next.

On using RLock, you are right. This is the one used in Observable. It is useful only on cycle graphs where zip depends on its own output, but everything is possible !

**Comment by mmpio** [comment]
We used the script at #505

**Pull request merged**
