### PR TITLE
fix InvalidStateError in to_future

### PR DESCRIPTION
**Pull request by frederikaalund**
Motivating example:

```python
import asyncio
import rx
from rx import operators as ops

async def _main():
    obs = rx.just(42)
    fut = next(obs.__await__())
    fut.cancel()
    await obs

asyncio.run(_main())
```

The above raises the following exception:
```python
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/scheduler/eventloop/asyncioscheduler.py", line 48, in interval
    sad.disposable = self.invoke_action(action, state=state)
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/scheduler/scheduler.py", line 103, in invoke_action
    ret = action(self, state)
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/core/observable/returnvalue.py", line 31, in action
    observer.on_completed()
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/core/observer/autodetachobserver.py", line 44, in on_completed
    self._on_completed()
  File "/home/fpa/.local/lib/python3.8/site-packages/rx/core/operators/tofuture.py", line 48, in on_completed
    future.set_result(last_value)
asyncio.exceptions.InvalidStateError: invalid state
```

The example is contrived but I encountered the same issue in production.

### CODE REVIEW

**Comment by frederikaalund** [comment]
I now also dispose the subscription when the future is done. This avoids leaking subscriptions on cancellation. See #502 for reference.

I've removed the comment that said "No cancellation can be done" since cancellation is now supported.

**Review by MainRo — CHANGES_REQUESTED** [review]
Thanks, that seems good to me.
Can you add some unit tests ?

**Comment by frederikaalund** [comment]
Thanks for having a look at this issue.

> Can you add some unit tests ?

I have added two unit tests.

Let me know if you need something else.

**Review by MainRo — APPROVED** [review]
Thanks!

**Pull request merged**
