### PR TITLE
Update Notebooks: Part One

### PR DESCRIPTION
**Pull request by J0**
Initial pull with updates for RxPy v4 -- I'm new to RxPy and am updating them as I go along so comments/advice is very much appreciated.

Thanks!

### CODE REVIEW

**Comment by J0** [comment]
Hey @dbrattli,

Sorry to trouble you -- do you mind approving the workflow? Would like to check if there's anything I should fix.

Thanks!

**Comment by J0** [comment]
Sorry @dbrattli could I also trouble you for a review while at it?

**Review by dbrattli — APPROVED** [review]
@J0 This is great work!! I'm currently on holiday with limited time to review, but I think this looks very good. The only suggestion I have is that we insert line breaks for the `.pipe()` method so that the arguments are on separate lines. But this is a minor stylish issue.

**Comment by J0** [comment]
Gotcha, that make sense! Will add the line breaks and move to next notebook. Thank you for reviewing this despite being on holiday -- please enjoy your break! I'll open the rest of the PRs in the future.

**Comment by J0** [comment]
Hey @dbrattli !

Hope the holiday went well! Was wondering if I could get help with re-running the workflow again since I'm still a first time contributor and still need approval. Won't need to bug you as much once we push this through

**Comment by J0** [comment]
Let me know if any further changes are needed!

**Comment by J0** [comment]
Hey @dbrattli,

Just want to check in  in case the last message got drowned in the motifs -- let me know if there are any further changes needed.

Thanks!

**Comment by dbrattli** [comment]
@J0 Looks great! Thanks a lot for your efforts. Feel free to merge.

**Comment by J0** [comment]
Hey @dbrattli 

CleanShot 2022-07-29 at 15 43 22@2x

Thanks! Don't think I can merge though 😅 Don't have permissions

**Pull request merged**
