### PR TITLE
Concat map

### PR DESCRIPTION
**Pull request by matiboy**
- tests inspired by [RxJS](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/concatMap-spec.ts)
- implementation from #581 [iyz91](https://github.com/iyz91) 's code
- documentation inspired by [RxJS](https://rxjs.dev/api/operators/concatMap)

### CODE REVIEW

**Review by dbrattli — APPROVED** [review]
@matiboy Thanks for adding this. Looks great!

**Comment by dbrattli** [comment]
One thing I suddenly realized is that we might not need the `_concat_map` file if we make the composition inside `__init__.py` e.g:

```py
return compose(operators. Map(project), operators. Merge(max_concurrent=1))
```

**Comment by matiboy** [comment]
> One thing I suddenly realized is that we might not need the `_concat_map` file if we make the composition inside `__init__.py` e.g:
> 
> ```python
> return compose(map(project), merge(max_concurrent=1))
> ```

Sorry mis-read initially and kept the "verbose" definition. But yes, beautiful one-liner.

**Comment by dbrattli** [comment]
Looks great. PS: another change we want to do is to borrow the `curry_flip` function from the Expression library to simplify all the operator implementations by removing all the nested functions. Take a look at https://github.com/cognitedata/Expression/blob/main/expression/collections/block.py#L602 Thus you can put `source` back as the first parameter, and curry-flip will move it as the last parameter curried (returning a function that takes it as the parameter). I can open an issue to discuss this more.

**Pull request merged**
